name: election_system_user
description: Online Election System User App
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-246.0.dev <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  get: ^4.6.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.1.0
  supabase_flutter: ^1.10.9
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0
  image_picker: ^1.0.1
  intl: any
  dartz: ^0.10.1
  supabase_auth_ui: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - .env

